### ISSUE TITLE
Given example does not work

### ISSUE THREAD

**Issue by devmarwat** [foxdeep/owl_detection_camera#4]
W/StreamingFormatChecker(27638): ML Kit has detected that you seem to pass camera frames to the detector as a Bitmap object. This is inefficient. Please use YUV_420_888 format for camera2 API or NV21 format for (legacy) camera API and directly pass down the byte array to ML Kit.
Please check out the issue and also remove text displayed in Chinese or Hindi language.
This example does not work at all.

**Comment by leechupe** [comment]
Hi Hassanmrwt:

We have already released the 0.2.5 version. Now you can update your lib. And the hints of text problems can use the OwlDetectionCamera.disableHint(bool value) function to disable the hints. Or you can change the hints of text to whatever you want by the OwlDetectionCamera.faceDetectHint(String aFitText, String aComeCloser, String  aBackward)  function. 

I hope this could help you.  Thank you for your reply.

**Comment by devmarwat** [comment]
Tested the latest version it works for QRcode detection perfectly but still does not detect faces in a live preview. I think the example needs improvement to match the latest version.
In the previous version, there were some issues with Permission Handling but this time it works fine.

**Comment by leechupe** [comment]
Hi,

Face detection part was working fine.  Can you please share the screenshot or the code that you used? Also, please share your device information.
